# Generated by Django 5.0.2 on 2024-03-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_remove_article_photo_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='description',
            field=models.TextField(),
        ),
    ]
