# Generated by Django 5.0.2 on 2024-05-04 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('wiki', '0005_alter_articlecategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('Article', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='wiki.article')),
                ('Author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='user_management.profile')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
