# Generated by Django 5.0.2 on 2024-05-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Author',
            new_name='author',
        ),
    ]
