# Generated by Django 5.0.2 on 2024-05-08 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_rename_article_comment_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wiki.article'),
        ),
    ]
