# Generated by Django 5.0.2 on 2024-05-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_alter_article_header_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
