# Generated by Django 5.0.2 on 2024-03-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='article',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='entry',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='description',
            field=models.TextField(),
        ),
    ]
