# Generated by Django 5.0.1 on 2024-05-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_commission_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('0', 'Open'), ('1', 'Full'), ('2', 'Completed'), ('3', 'Discontinued')], default='Open', max_length=12),
        ),
    ]
